# Workflow name
name: firt-project-cicd

# Triggers for the workflow
on:
  # Manual trigger using the workflow_dispatch event
  workflow_dispatch:

  # Automatic trigger on push events to the main branch
  push:
    branches:
      - main

  # Automatic trigger on pull request events targeting the main branch
  pull_request:
    branches:
      - main

  # Scheduled trigger at 5:00 AM UTC, Monday through Friday
  schedule: 
    - cron: '0 0 * * 0'
    
env:
  date: 29-04-2034    
  
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20, 18]
        platform: [ubuntu-latest, macos-latest, windows-latest]
        exclude:
          - platform: macos-latest
            node-version: 20
      fail-fast: false
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          
      - name: Install Dependencies
        run: npm install

      - name: Build and Test
        run: npm run build && npm run test
        continue-on-error: true
    
   # Run the linter.
      - name: Run lint
        run: npm run test-lint
      
         # Send a console message at completion.
      - run: |
          "Hello [username of the user who initiated the run]. You pushed to [repository_name] at $(date)."."
